<h1 align="center">OlÃ¡ ğŸ‘‹, sou Thayliny</h1>
<h3 align="center">Um apaixonado gerente de projetos do Brasil</h3>

- ğŸ”­ Atualmente estou trabalhando em **Projeto de Desenvolvimento de Software**

- ğŸŒ± Atualmente estou aprendendo **ProgramaÃ§Ã£o em Java**

- ğŸ‘¯ Pretendo colaborar na **ExperiÃªncia do usuÃ¡rio**

- ğŸ¤ Estou procurando ajuda com **Scrum**

- ğŸ‘¨â€ğŸ’» Todos os meus projetos estÃ£o disponÃ­veis em [https://github.com/thayliny](https://github.com/thayliny)

- ğŸ“ Escrevo regularmente artigos sobre [https://web.dio.me/users/thayliny_alvesmoura?tab=achievements](https://web.dio.me/users/thayliny_alvesmoura?tab=achievements)

- ğŸ’¬ Pergunte-me sobre **Trabalho**

- ğŸ“« Como entrar em contato comigo **thayliny.Alvesmoura@gmail.com**

- âš¡ Curiosidade **nÃ£o sei inglÃªs**

<h3 align="left">Conecte-se comigo:</h3>
<p alinhar="esquerda">
<a href="https://linkedin.com/in/https://www.linkedin.com/in/thayliny-moura-706234157/" target="blank"><img align="center" src=" https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="https://www.linkedin.com /in/thayliny-moura-706234157/" height="30" width="40" /></a>
</p>

<h3 align="left">Idiomas e ferramentas:</h3>
<p align="left"> <a href="https://developer.android.com" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons /devicon/master/icons/android/android-original-wordmark.svg" alt="android" width="40" height="40"/> </a> <a href="https://aws.amazon .com" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg" alt=" aws" width="40" height="40"/> </a> <a href="https://www.cprogramming.com/" target="_blank" rel="noreferrer"> <img src=" https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg" alt="c" width="40" height="40"/> </a> <a href ="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3 /css3-original-wordmark.svg" alt="css3" width="40" height="40"/> </a> <a href="https://www.figma.com/" target="_blank " rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/figma/figma-icon.svg" alt="figma" width="40" height="40"/> < /a> <a href="https://flutter.dev" target="_blank" rel="noreferrer"> <img src="https://www.vectorlogo.zone/logos/flutterio/flutterio-icon. svg" alt="flutter" width="40" height="40"/> </a> <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer "> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40" /> </a> <a href="https://www.java.com" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon /master/icons/java/java-original.svg" alt="java" width="40" height="40"/> </a> <a href="https://developer.mozilla.org/en -US/docs/Web/JavaScript" target="_blank" rel="noreferrer"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg " alt="javascript" width="40" height="40"/> </a> <a href="https://www.mysql.com/" target="_blank" rel="noreferrer"> < img src = "https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg" alt="mysql" width="40" height="40"/> </a> <a href="https://developer.apple.com/swift/" target="_blank" rel="noreferrer "> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/swift/swift-original.svg" alt="swift" width="40" height="40"/> </a> </p>




